name: 04 - Using Actions
# on: push
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.11.0"
      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app
      - name: Run Tests
        run: npm run test
        working-directory: 04-using-actions/react-app
