name: 07 - Using Expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.branch }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ Runner.os }}"
      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug }} && ${{ github.branch == 'main' }}
        run: |
          echo "I was triggered from main"
      - name: "Greeting"
        run: |
          echo "Hello, world"
