name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Whether to execute cache step"
        type: boolean
        default: true
      node-version:
        type: choice
        description: "Node.js version to use"
        options:
          - "24.11.0"
          - "20.5.1"
          - "18.16.0"
        default: "24.11.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version}}
      - name: Download cached dependenceis
        id: cache
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
          path: 13-caching/react-app/node_modules
          key: $ {{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: "13-caching/react-app"
        run: npm ci
      - name: Testing
        working-directory: "13-caching/react-app"
        run: npm run test
      - name: Building
        working-directory: "13-caching/react-app"
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
